<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RootElement" nsURI="http:///RootElement.ecore" nsPrefix="RootElement">
  <eClassifiers xsi:type="ecore:EClass" name="Timer">
    <eOperations name="startClockTick" ordered="false" lowerBound="1"/>
    <eOperations name="resetClockTick" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClockTick" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eOperations name="turnPedLightGreen" ordered="false" lowerBound="1"/>
    <eOperations name="turnCarLightGreen" ordered="false" lowerBound="1"/>
    <eOperations name="callStartClockTick" ordered="false" lowerBound="1"/>
    <eOperations name="callResetClockTick" ordered="false" lowerBound="1"/>
    <eOperations name="turnPedLightRed" ordered="false" lowerBound="1"/>
    <eOperations name="turnCarLightYellow" ordered="false" lowerBound="1"/>
    <eOperations name="turnCarLightRed" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PedestrianLight">
    <eOperations name="buttonPressed" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eOperations name="isPedLightGreen" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eOperations name="isPedLightRed" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pedesterianLightType" ordered="false"
        lowerBound="1" eType="#//PedesterianLightType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="button_Pressed_Type" ordered="false"
        lowerBound="1" eType="#//ButtonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPedLight" ordered="false"
        lowerBound="1" eType="#//PedesterianLightType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PedesterianLightType">
    <eLiterals name="Red"/>
    <eLiterals name="Green" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ButtonType">
    <eLiterals name="ButtonA"/>
    <eLiterals name="ButtonB" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CarLight">
    <eOperations name="isGreen" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eOperations name="isYellow" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eOperations name="isRed" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="carLightType" ordered="false"
        lowerBound="1" eType="#//CarLightType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentCarLight" ordered="false"
        lowerBound="1" eType="#//CarLightType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CarLightType">
    <eLiterals name="Green"/>
    <eLiterals name="Yellow" value="1"/>
    <eLiterals name="Red" value="2"/>
  </eClassifiers>
</ecore:EPackage>
